// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgruvdbqnedomhsmzkfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZncnV2ZGJxbmVkb21oc216a2ZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNTEzMTEsImV4cCI6MjA2NTcyNzMxMX0.O3ER07NOFI8tWsr2L8BwPaUb4acW4HBOXZVMFxIxx58";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);